services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=appdb
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppassword
    volumes:
      - db_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql:ro
    restart: unless-stopped

volumes:
  db_data:
